### ISSUE TITLE
Create GitHub account and send username to Luke

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/research#21]
So I can add you to the team.

**Comment by omarsilverman** [comment]
Hello Mr. @lwjohnst86 trying to catch up with the common docs :)

**Comment by lwjohnst86** [comment]
@omarsilverman Invited you :wink:

**Comment by lassebjerg** [comment]
Hello Mr. @lwjohnst86 trying to catch up with the common docs :)
