### ISSUE TITLE
Updating website

### ISSUE THREAD

**Issue by danielibsen** [steno-aarhus/research#43]
Hi everyone. This is a thread where you can come with all your suggestions for updates to the website. 

Maybe we can discuss the list at the planning meeting in December and hopefully assign some people to update different things or add new content to the website. 

Also, please look at some of the other issues on under the tab "issues". There are already a lot of good ideas for the website.

**Comment by danielibsen** [comment]
Here are my notes: 

Question: How are the common docs working thus far? Are people using the website?

- Onboarding
  - Buddy system – is it working?
  - Update information in table with Maria – new stuff since moved to Forum
  - Could we have a whole section on going to conferences – what are the basic steps – tips for planning which conferences to go to, how to arrange the trip, how to do expenses, getting the most out of a conference, making a poster, giving a talk, printing the poster etc.? – could we make a calendar of the conferences we plan to go to during the year – things we plan during the yearly meeting?
  - Could we have like a year-wheel with central activities at SDCA for researchers?
  - Do we need to mention the typical setup by either being employed by the Region vs AU?
  - Update parking info
  - Journal clubs – could we have an epi methods journal club?
  - Need table for PhD students
- Support
 - Data analysis tips and help
   - Put the figure about help in the top
   - Add more explanatory text
   - What about rules re data safety – at least put a link to relevant courses and rules we follow
   - Various data sources
   - Add UK Biobank
- Organization
  - Research groups – are they still the same?
  - There could be more info about us – at least our different research areas

**Comment by lwjohnst86** [comment]
Lots have changed since this issue, will close for now.
